server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
  jpa:
    database-patform: org.hibernate.dialect.MYSQL8Dialect
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: springbankRootPsw

security:
  oauth2:
    resource:
      jwt:
        key-value: obarbierSigningKey